modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory
license="MIT"

[[mods]] #mandatory
modId="freelook" #mandatory
version="${version}" #mandatory
displayName="FreeLook" #mandatory
description='''FPS Style FreeLook!''' #mandatory
authors="jmilthedude" #optional

[[dependencies.freelook]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.freelook]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,)"
    ordering="NONE"
    side="BOTH"