modLoader="javafml" #mandatory
loaderVersion="[34,)" #mandatory
license="All rights reserved"

[[mods]] #mandatory
modId="freelook" #mandatory
version="1.3.2" #mandatory
displayName="FreeLook" #mandatory
description='''FPS Style FreeLook!''' #mandatory

[[dependencies.freelook]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.freelook]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,)"
    ordering="NONE"
    side="BOTH"